AllCops:
  Include:

    - config.ru
  Exclude:
    - config/**
    - db/**
    - Rakefile
    - db/schema.rb
    - test/test_helper.rb
    - config/initializers/devise.rb

# Configuration parameters: Exclude.
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/**/*'

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

LineLength:
  Max: 120