AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/schema.rb

# Configuration parameters: Exclude.
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/**/*'

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'